VTRANS3_SOURCE_FILES.MK_SOURCE_FILES := \
	VTrans3/Attributes/EnglishWord.cpp\
	VTrans3/Attributes/GermanWord.cpp\
	VTrans3/Attributes/PositionString.cpp\
	VTrans3/Attributes/Token.cpp\
	VTrans3/Attributes/Word.cpp\
	VTrans3/Controller/DictReaderAndVocAccess/TUchemnitzEngWordSorted1stAndBinarySearch.cpp\
	VTrans3/Controller/DictReaderAndVocAccess/TUchemnitzEngWordSorted1stAndBinarySearch_test.cpp\
	VTrans3/Controller/DynLib/dynlib_main.cpp\
	VTrans3/Controller/DynLib/vtrans_dynlib_VTransDynLibJNI.cpp\
	VTrans3/Controller/TranslateControllerBaseReturnCodeDescriptons.cpp\
	VTrans3/Controller/TranslationControllerBase.cpp\
	VTrans3/IO/ConfigurationReader.cpp\
	VTrans3/IO/ConfigurationReader_test.cpp\
	VTrans3/IO/dictionary/DictionaryReaderBase.cpp\
	VTrans3/IO/dictionary/TUchemnitz/EngWordSorted1st/BinarySearchInDictFile.cpp\
	VTrans3/IO/dictionary/TUchemnitz/EngWordSorted1st/eachAttributeInSingleLine/EachAttributeInSingleLine.cpp\
	VTrans3/IO/GenerateXMLtreeFromParseTree.cpp\
	VTrans3/IO/MiniXML/GrammarRuleFileReader.cpp\
	VTrans3/IO/MiniXML/MainConfigFileReader.cpp\
	VTrans3/IO/MiniXML/TranslationRuleFileReader.cpp\
	VTrans3/IO/MiniXML/TranslationRuleFile_EndXMLelement.cpp\
	VTrans3/IO/MiniXML/VocAttributeDefintionHandler.cpp\
	VTrans3/IO/MiniXMLconfigReader.cpp\
	VTrans3/IO/ParseTree2XMLtreeTraverser.cpp\
	VTrans3/IO/rules/TranslationRuleFileReaderBase.cpp\
	VTrans3/IO/TinyXMLconfigReader.cpp\
	VTrans3/IO/UnknownGrammarPartNameException.cpp\
	VTrans3/Parse/DirectingLeavesInSingleIterationTraverser.cpp\
	VTrans3/Parse/DirectingLeavesMultipleIterTraverser.cpp\
	VTrans3/Parse/GrammarPart.cpp\
	VTrans3/Parse/KeepTrackOfCurrentParseTreePath.cpp\
	VTrans3/Parse/ParseByRise.cpp\
	VTrans3/Parse/ParseByRise_BuildParseTree.cpp\
	VTrans3/Parse/ParseByRise_GrammarRule.cpp\
	VTrans3/Translate/AddVocAndTranslDefinitions.cpp\
	VTrans3/Translate/AttributeTypeAndPosAndSize.cpp\
	VTrans3/Translate/ConditionsAndTranslation.cpp\
	VTrans3/Translate/InsertIntoTreeTransverser.cpp\
	VTrans3/Translate/SetSameConsecutiveIDforLeaves.cpp\
	VTrans3/Translate/SummarizePersonIndex.cpp\
	VTrans3/Translate/SyntaxTreePath.cpp\
	VTrans3/Translate/TransformationRule.cpp\
	VTrans3/Translate/TransformTreeTraverser.cpp\
	VTrans3/Translate/TranslatedTreeTraverser.cpp\
	VTrans3/Translate/TranslateParseByRiseTree.cpp\
	VTrans3/Translate/TranslateTreeTraverser.cpp\
	VTrans3/Translate/TranslationRule.cpp\
	VTrans3/VocabularyInMainMem/CharMappedDictionary.cpp\
	VTrans3/VocabularyInMainMem/CharStringStdMap/CharStringStdMap.cpp\
	VTrans3/VocabularyInMainMem/IVocabularyInMainMem.cpp\
	VTrans3/VocabularyInMainMem/I_WordSearch.cpp\
	VTrans3/VocabularyInMainMem/TUchemnitzEngWordSorted1st/BinarySearchInDictFile.cpp\
	VTrans3/VocabularyInMainMem/TUchemnitzEngWordSorted1st/BinarySearchInDictFile_test.cpp\
	VTrans3/VocabularyInMainMem/VocabularyAndTranslation.cpp\
